In [8]:
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
import numpy as np

In [9]:
path = 'C:/Users/Summer/Desktop/Fall2019-proj3-sec1--grp5-master/data/'
dat_train = pd.read_csv(path + "dat_train.csv")
dat_test = pd.read_csv(path + 'dat_test.csv')
dat_full = pd.concat([dat_train, dat_test], ignore_index = True)
dat_full.head()

,Unnamed: 0,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,...,feature5998,feature5999,feature6000,feature6001,feature6002,feature6003,feature6004,feature6005,feature6006,emotion_idx
0,1,31,18,1,20,33,20,1,17,151,...,98,150,202,50,102,154,52,104,52,21
1,2,35,15,6,27,39,20,2,17,151,...,104,159,213,54,109,163,55,109,54,11
2,3,35,17,2,20,32,14,3,20,165,...,99,152,204,52,105,157,53,105,52,2
3,4,33,16,3,20,29,12,6,23,161,...,101,156,210,54,109,163,55,109,54,7
4,5,29,15,1,17,27,13,2,17,133,...,83,128,172,44,89,133,45,89,44,1

In [26]:
#y = dat_full["emotion_idx"]

In [28]:
X, y = dat_full.iloc[:,:-1],dat_full.iloc[:,-1]

In [29]:
y = y-1

In [30]:
X = StandardScaler().fit_transform(X)
pca = PCA(n_components=1000)
principalComponents = pca.fit_transform(X)
std_X = pd.DataFrame(principalComponents)
std_X.head()

C:\Users\Summer\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Summer\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
0,17.941942,-7.482042,-17.903079,-21.097911,-0.903790,-5.626527,4.713359,15.174499,-5.479774,-14.978505,...,0.001949,0.010909,-0.025694,0.033578,0.026616,-0.033084,0.047626,-0.015569,0.036819,-0.023939
1,-3.576553,5.954796,29.516030,-3.804396,2.637288,2.558617,-12.504832,15.610126,-16.519389,-8.920135,...,0.032388,-0.008670,0.013074,-0.025337,0.030237,0.044361,0.018166,-0.068477,0.068011,0.061947
2,28.318747,18.633017,4.623768,16.793613,-18.896898,-32.430227,6.019863,-5.066719,7.110168,-2.475816,...,0.005749,0.009466,0.010295,-0.076364,-0.036414,0.040375,0.026119,-0.022036,0.043619,0.017354
3,24.822229,-11.953959,4.662067,-8.792684,-22.668086,-10.910817,7.808467,2.841391,-15.029764,13.124704,...,0.039806,-0.015663,0.025027,-0.023156,-0.079642,-0.014192,-0.059896,0.070580,0.007263,-0.097178
4,-46.063489,34.670466,-24.841280,-22.743334,0.801309,-0.373970,0.587349,-5.935386,1.165511,-4.673531,...,0.027746,-0.008829,-0.018180,0.057460,-0.019153,0.016108,-0.064334,0.024750,0.073938,-0.022191

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

In [107]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100, criterion = 'gini', random_state = 42, min_samples_leaf=1,max_features='sqrt')
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='sqrt', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [108]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
print(pd.crosstab(y_test, y_pred, rownames=['Actual'], colnames=['Predicted']))

Predicted  0   1   2   3   4   5   6   7   8   9   ...  12  13  14  15  16  \
Actual                                             ...
0          16   0   4   1   0   0   1   0   0   1  ...   0   0   0   3   0
1           0  18   0   0   0   0   0   3   4   0  ...   0   0   0   0   0
2           4   0  10   0   0   1   1   0   0   1  ...   0   0   0   1   0
3           2   0   0   7   0   0   0   0   0   2  ...   1   0   0   0   0
4           0   0   1   0   9   0   0   0   0   0  ...   0   0   0   0   1
5           1   1   1   4   0   9   0   0   0   0  ...   1   1   0   2   0
6           0   0   0   1   3   0   8   0   0   0  ...   0   0   0   0   2
7           0   2   0   0   0   0   0  18   1   0  ...   0   0   0   0   0
8           1   2   0   0   0   0   1   0   9   0  ...   0   0   0   0   0
9           0   0   4   6   0   0   0   0   0   8  ...   2   0   0   0   0
10          0   0   1   4   0   1   0   0   0   4  ...   1   0   1   0   0
11          0   0   0   1   0   1   0   0   0   0  ...   2   0   0   0   0
12          2   0   2   7   0   0   0   0   0   4  ...   2   0   1   0   0
13          0   0   0   0   1   0   2   0   0   0  ...   0  15   4   0   0
14          0   0   1   0   4   0   1   0   0   0  ...   0   0   7   0   2
15          1   1   2   0   1   1   0   0   0   3  ...   0   1   0  17   1
16          0   0   0   0   2   0   0   4   0   0  ...   0   0   0   2  13
17          2   0   1   0   4   0   1   2   0   0  ...   0   0   1   0   6
18          0   0   1   0   0   0   0   0   1   0  ...   1   3   0   1   4
19          0   0   0   0   0   0   0   0   3   0  ...   0   1   2   0   2
20          0   0   0   1   0   1   0   0   2   0  ...   0   2   1   0   0
21          0   0   6   3   0   2   2   0   0   1  ...   0   0   0   0   0

Predicted  17  18  19  20  21
Actual
0           0   0   0   0   0
1           0   0   0   0   0
2           0   1   0   0   2
3           0   0   0   0   1
4           2   0   0   0   0
5           0   0   0   0   0
6           1   0   2   1   0
7           0   0   0   0   0
8           0   1   1   1   0
9           0   0   0   0   0
10          0   0   0   2   0
11          0   1   0   1   0
12          0   0   0   1   2
13          0   0   1   1   1
14          0   1   0   0   0
15          0   0   0   0   0
16          2   0   0   0   0
17          2   1   1   0   0
18          1   8   2   4   3
19          0   1   5   4   0
20          0   3   2   9   0
21          0   3   1   2   3

[22 rows x 22 columns]

In [109]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 41.60%